FROM golang:1.18

WORKDIR /go/src/app

COPY wait-for-it.sh ./

COPY cmd/server cmd/server
COPY internal internal/
COPY api api/
COPY go.mod go.sum ./
RUN go mod download
RUN go build -o server cmd/server/main.go

CMD ["./server"]