FROM golang:1.18

WORKDIR /go/src/app

COPY wait-for-it.sh ./

COPY cmd/client cmd/client/
COPY internal internal/
COPY api api/
COPY go.mod go.sum ./
RUN go mod download
RUN go build -o client cmd/client/main.go

ENTRYPOINT ["./client"]