version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: books
    ports:
      - 3306:3306
    volumes:
      - mysqldbvolume:/var/lib/mysql

  server:
    container_name: server
    depends_on:
      - db
    build:
      context: ../
      dockerfile: deployments/Dockerfile.server
    ports:
     - 50051:50051
    command: ["./wait-for-it.sh", "db:3306", "--", "./server", "-port", "50051", "-db", "root:pass@(db)/books?multiStatements=true"]

volumes:
  mysqldbvolume:
    driver: local
