// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/booksearch.proto

package kvadotest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookSearchClient is the client API for BookSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookSearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
}

type bookSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewBookSearchClient(cc grpc.ClientConnInterface) BookSearchClient {
	return &bookSearchClient{cc}
}

func (c *bookSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := c.cc.Invoke(ctx, "/booksearch.BookSearch/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookSearchServer is the server API for BookSearch service.
// All implementations must embed UnimplementedBookSearchServer
// for forward compatibility
type BookSearchServer interface {
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	mustEmbedUnimplementedBookSearchServer()
}

// UnimplementedBookSearchServer must be embedded to have forward compatible implementations.
type UnimplementedBookSearchServer struct {
}

func (UnimplementedBookSearchServer) Search(context.Context, *SearchRequest) (*SearchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedBookSearchServer) mustEmbedUnimplementedBookSearchServer() {}

// UnsafeBookSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookSearchServer will
// result in compilation errors.
type UnsafeBookSearchServer interface {
	mustEmbedUnimplementedBookSearchServer()
}

func RegisterBookSearchServer(s grpc.ServiceRegistrar, srv BookSearchServer) {
	s.RegisterService(&BookSearch_ServiceDesc, srv)
}

func _BookSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booksearch.BookSearch/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookSearch_ServiceDesc is the grpc.ServiceDesc for BookSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booksearch.BookSearch",
	HandlerType: (*BookSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _BookSearch_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/booksearch.proto",
}
